<?xml version="1.0"?>
<doc>
    <assembly>
        <name>AutoCADLibrary</name>
    </assembly>
    <members>
        <member name="T:AutoCADLibrary.ColorUtil">
            <summary>
            색깔에 대한 명령을 가지고 있는 클래스입니다.
            </summary>
        </member>
        <member name="M:AutoCADLibrary.ColorUtil.GetColorByDialog(System.Boolean)">
            <summary>
            색깔을 선택하는 창을 띄워 사용자가 선택한 색을 가져옵니다.
            </summary>
            <param name="ShowByLayerByBlock">ByLayer, ByBlock에 대한 선택이 유효한지를 결정합니다.</param>
            <returns>Autodesk.AutoCAD.Colors.Color가 리턴됩니다.</returns>
        </member>
        <member name="M:AutoCADLibrary.ColorUtil.GetColorByIndex(System.Int16)">
            <summary>
            인덱스에 따른 색깔을 나타냅니다.
            </summary>
            <param name="index"></param>
            <returns></returns>
        </member>
        <member name="P:AutoCADLibrary.ColorUtil.ByLayer">
            <summary>
            ByLayer에 대한 색깔 값을 리턴합니다.
            </summary>
        </member>
        <member name="P:AutoCADLibrary.ColorUtil.ByBlock">
            <summary>
            ByBlock에 대한 색깔 값을 리턴합니다.
            </summary>
        </member>
        <member name="T:AutoCADLibrary.DatabaseUtil">
            <summary>
            AutoCAD Database에 대한 명령을 가지고 있는 클래스입니다.
            </summary>
        </member>
        <member name="M:AutoCADLibrary.DatabaseUtil.GetTransaction(Autodesk.AutoCAD.DatabaseServices.Database)">
            <summary>
            database의 새로운 트랜잭션을 만들고 반환합니다.
            </summary>
            <param name="database">새로운 트랜잭션을 만들 database</param>
            <returns></returns>
        </member>
        <member name="M:AutoCADLibrary.DatabaseUtil.GetDatabase(Autodesk.AutoCAD.ApplicationServices.Document)">
            <summary>
            사용하지 않습니다.
            </summary>
            <param name="document">Datbase를 가져올 Document 입니다.</param>
            <returns></returns>
        </member>
        <member name="M:AutoCADLibrary.DatabaseUtil.GetEditor(Autodesk.AutoCAD.ApplicationServices.Document)">
            <summary>
            사용하지 않습니다.
            </summary>
            <param name="document">Editor를 가져올 Document 입니다.</param>
            <returns></returns>
        </member>
        <member name="T:AutoCADLibrary.EntityUtil">
            <summary>
            객체에 대한 명령들을 가지고 있는 클래스 입니다.
            </summary>
        </member>
        <member name="M:AutoCADLibrary.EntityUtil.EraseEntities(Autodesk.AutoCAD.DatabaseServices.ObjectIdCollection)">
            <summary>
            객체들을 지웁니다.
            </summary>
            <param name="entityIds">지울 객체의 ObjectId입니다.</param>
        </member>
        <member name="M:AutoCADLibrary.EntityUtil.InsertEntity(Autodesk.AutoCAD.DatabaseServices.Entity)">
            <summary>
            객체를 삽입합니다.
            </summary>
            <param name="entity">삽입할 객체입니다.</param>
        </member>
        <member name="M:AutoCADLibrary.EntityUtil.InsertEntities(System.Collections.Generic.IEnumerable{Autodesk.AutoCAD.DatabaseServices.Entity})">
            <summary>
            객체들을 삽입합니다.
            </summary>
            <param name="entities">삽입할 객체들 입니다.</param>
        </member>
        <member name="M:AutoCADLibrary.EntityUtil.CreateGroup(System.String,Autodesk.AutoCAD.DatabaseServices.ObjectIdCollection)">
            <summary>
            objectIds에 들어있는 객체들로 group 객체를 생성합니다.
            </summary>
            <param name="groupName">Group의 이름입니다.</param>
            <param name="objectIds">객체의 ID들 입니다.</param>
            <returns></returns>
        </member>
        <member name="T:AutoCADLibrary.FileUtil">
            <summary>
            파일 관리에 대한 명령어를 가지고 있는 클래스입니다.
            </summary>
        </member>
        <member name="M:AutoCADLibrary.FileUtil.GetSaveFilePath(System.String,System.String,System.String)">
            <summary>
            파일 저장 대화상자를 띄워 사용자가 지정한 저장경로를 가져옵니다.
            </summary>
            <param name="title">대화상자의 제목</param>
            <param name="initialDirectory">대화상장의 초기 폴더 위치</param>
            <param name="filter">대화상자에 표시할 저장 형식</param>
            <returns>사용자가 지정한 저장경로입니다.</returns>
        </member>
        <member name="M:AutoCADLibrary.FileUtil.GetOpenFilePath(System.String,System.String,System.String)">
            <summary>
            파일 저장 대화상자를 띄워 사용자가 지정한 파일경로를 가져옵니다.
            </summary>
            <param name="title">대화상자의 제목</param>
            <param name="initialDirectory">대화상장의 초기 폴더 위치</param>
            <param name="filter">대화상자에 표시할 파일 형식</param>
            <returns>사용자가 지정한 파일경로입니다.</returns>
        </member>
        <member name="T:AutoCADLibrary.XDataUtil">
            <summary>
            XData에 대한 명령이 들어있는 클래스입니다.
            </summary>
        </member>
        <member name="T:AutoCADLibrary.GeometryUtil">
            <summary>
            점, 벡터, 각도 등에 관련된 명령을 가지고 있는 클래스입니다.
            </summary>
        </member>
        <member name="M:AutoCADLibrary.GeometryUtil.ToPoint2d(Autodesk.AutoCAD.Geometry.Point3d)">
            <summary>
            Point3d 좌표를 Point2d로 변환합니다.
            </summary>
            <param name="Point">변환할 좌표입니다.</param>
            <returns>변환된 좌표 Point2d를 리턴합니다.</returns>
        </member>
        <member name="M:AutoCADLibrary.GeometryUtil.ToPoint3d(Autodesk.AutoCAD.Geometry.Point2d)">
            <summary>
            Point2d 좌표를 Point3d로 변환합니다.
            </summary>
            <param name="Point">변환할 좌표입니다.</param>
            <returns>변환된 좌표 Point3d를 리턴합니다.</returns>
        </member>
        <member name="M:AutoCADLibrary.GeometryUtil.GetMinMaxPoint(Autodesk.AutoCAD.DatabaseServices.ObjectId)">
            <summary>
            객체의 최대(오른쪽위), 최소(왼쪽아래) 점을 가져옵니다.
            </summary>
            <param name="EntityId">점을 가져올 객체의 ObjectId 입니다.</param>
            <returns>[0]:MinPoint, [1]:MaxPoint</returns>
        </member>
        <member name="M:AutoCADLibrary.GeometryUtil.IsEqualPoint(Autodesk.AutoCAD.Geometry.Point3d,Autodesk.AutoCAD.Geometry.Point3d,System.Double)">
            <summary>
            point1과 point2가 tolerance 오차 내에서 같은지 반환합니다.
            </summary>
            <param name="point1">비교할 점1 입니다.</param>
            <param name="point2">비교할 점2 입니다.</param>
            <param name="tolerance">같다고 볼 오차범위 입니다.</param>
            <returns></returns>
        </member>
        <member name="M:AutoCADLibrary.GeometryUtil.IsEqualPoint(Autodesk.AutoCAD.Geometry.Point2d,Autodesk.AutoCAD.Geometry.Point2d,System.Double)">
            <summary>
            point1과 point2가 tolerance 오차 내에서 같은지 반환합니다.
            </summary>
            <param name="point1">비교할 점1 입니다.</param>
            <param name="point2">비교할 점2 입니다.</param>
            <param name="tolerance">같다고 볼 오차범위 입니다.</param>
            <returns></returns>
        </member>
        <member name="T:AutoCADLibrary.LayerUtil">
            <summary>
            레이어에 대한 명령들을 가지고 있는 클래스 입니다.
            </summary>
        </member>
        <member name="M:AutoCADLibrary.LayerUtil.AddLayer(System.String,Autodesk.AutoCAD.Colors.Color)">
            <summary>
            레이어를 추가하는 메소드입니다. 레이어가 존재한다면, 그 레이어의 색깔만 바꿔줍니다.
            </summary>
            <param name="LayerName">추가할 레이어의 이름입니다.</param>
            <param name="AcadColor">추가할 레이어의 색깔입니다.</param>
            <returns>추가한 레이어의 ObjectId를 리턴합니다.</returns>
        </member>
        <member name="M:AutoCADLibrary.LayerUtil.LockLayer(System.String,System.Boolean)">
            <summary>
            레이어를 잠그거나, 풉니다.
            </summary>
            <param name="LayerName">작업할 레이어 이름입니다.</param>
            <param name="Lock">잠금여부</param>
            <returns>레이어의 ObjectId를 리턴합니다.</returns>
        </member>
        <member name="M:AutoCADLibrary.LayerUtil.OnOffLayer(System.String,System.Boolean)">
            <summary>
            레이어의 표시 여부를 바꿉니다.
            </summary>
            <param name="LayerName">작업할 레이어의 이름입니다.</param>
            <param name="onOff">레이어를 표시할지 표시하지 않을지 입니다.(true = 표시)</param>
            <returns>레이어의 ObjectId를 리턴합니다.</returns>
        </member>
        <member name="M:AutoCADLibrary.LayerUtil.GetLayerList(Autodesk.AutoCAD.DatabaseServices.Database)">
            <summary>
            database가 가지고있는 레이어를 가지고 옵니다.
            </summary>
            <param name="database">레이어 목록을 가져올 database입니다.</param>
            <returns></returns>
        </member>
        <member name="M:AutoCADLibrary.PolylineUtil.CreatePolyline(Autodesk.AutoCAD.Geometry.Point3d[],System.String,Autodesk.AutoCAD.Colors.Color,System.Boolean)">
            <summary>
            Coordinates의 좌표로 LW폴리선을 만들어줍니다.
            </summary>
            <param name="Coordinates">Point3d 정점들의 좌표</param>
            <param name="LayerName">폴리선에 적용될 레이어 이름</param>
            <param name="AcadColor">폴리선에 적용될 색깔</param>
            <param name="isClosed">닫힘, 열림 여부</param>
            <returns>폴리선을 만들어 리턴하여 줍니다.</returns>
        </member>
        <member name="M:AutoCADLibrary.PolylineUtil.CreatePolyline(Autodesk.AutoCAD.Geometry.Point3dCollection,System.String,Autodesk.AutoCAD.Colors.Color,System.Boolean)">
            <summary>
            Coordinates의 좌표로 LW폴리선을 만들어줍니다.
            </summary>
            <param name="Coordinates">Point3d 정점들의 좌표</param>
            <param name="LayerName">폴리선에 적용될 레이어 이름</param>
            <param name="AcadColor">폴리선에 적용될 색깔</param>
            <param name="isClosed">닫힘, 열림 여부</param>
            <returns>폴리선을 만들어 리턴하여 줍니다.</returns>
        </member>
        <member name="M:AutoCADLibrary.PolylineUtil.ToPolyline(Autodesk.AutoCAD.DatabaseServices.Curve)">
            <summary>
            
            </summary>
            <param name="curve"></param>
            <returns></returns>
        </member>
        <member name="T:AutoCADLibrary.PromptUtil">
            <summary>
            객체 선택, 프롬프트 창에 대한 명령들을 가지고 있는 클래스입니다.
            Coded By KevinSung
            </summary>
        </member>
        <member name="M:AutoCADLibrary.PromptUtil.GetEntity(System.String,System.Type[])">
            <summary>
            사용자가 선택한 객체를 가져오는 메소드 입니다.
            </summary>
            <param name="message">선택 전, 프롬프트에 표시할 메시지</param>
            <param name="Filter">선택이 가능하게 할 객체의 종류(클래스)</param>
            <returns>선택한 객체의 ObjectId를 리턴하며, ESC 등의 취소를 받았을 경우, ObjectId.Null 값을 리턴합니다.</returns>
        </member>
        <member name="M:AutoCADLibrary.PromptUtil.GetEntityResult(System.String,System.Type[])">
            <summary>
            사용자가 선택한 객체를 가져오는 메소드 입니다.
            </summary>
            <param name="message">선택 전, 프롬프트에 표시할 메시지</param>
            <param name="Filter">선택이 가능하게 할 객체의 종류(클래스)</param>
            <returns>객체를 선택했을 때, PromptEntityResult를 리턴합니다.</returns>
        </member>
        <member name="M:AutoCADLibrary.PromptUtil.GetEntitiesByWindow(Autodesk.AutoCAD.Geometry.Point3d,Autodesk.AutoCAD.Geometry.Point3d,Autodesk.AutoCAD.DatabaseServices.TypedValue[])">
            <summary>
            pt1과 pt2를 기준으로 사각형 내의 객체를 가져오는 메소드입니다.
            </summary>
            <param name="pt1">첫번째점</param>
            <param name="pt2">두번째점</param>
            <param name="Filter">선택이 가능하게 할 조건</param>
            <returns></returns>
        </member>
        <member name="M:AutoCADLibrary.PromptUtil.GetEntities(System.String,Autodesk.AutoCAD.DatabaseServices.TypedValue[])">
            <summary>
            사용자가 선택한 여러 객체들을 가져오는 메소드입니다.
            </summary>
            <param name="message">선택 전, 프롬프트에 표시할 메시지</param>
            <param name="Filter">선택이 가능하게 할 조건</param>
            <returns></returns>
        </member>
        <member name="M:AutoCADLibrary.PromptUtil.GetAllEntities(Autodesk.AutoCAD.DatabaseServices.TypedValue[])">
            <summary>
            화면상의 모든 객체들을 가져오는 메소드입니다.
            </summary>
            <param name="Filter">선택이 가능하게 할 조건</param>
            <returns></returns>
        </member>
        <member name="M:AutoCADLibrary.PromptUtil.GetPoint(System.String)">
            <summary>
            사용자가 선택한 점을 가져오는 메소드입니다.
            </summary>
            <param name="message">선택 전, 프롬프트에 표시할 메시지</param>
            <returns>지정한 점의 Point3d 좌표</returns>
        </member>
        <member name="M:AutoCADLibrary.PromptUtil.GetPoint(Autodesk.AutoCAD.Geometry.Point3d,System.String)">
            <summary>
            사용자가 선택한 점을 가져오는 메소드입니다. 점을 선택할 때, BasePoint를 기준으로 대쉬라인이 함께 나타납니다.
            </summary>
            <param name="message">선택 전, 프롬프트에 표시할 메시지</param>
            <param name="BasePoint">기준점의 좌표</param>
            <returns>지정한 점의 Point3d 좌표</returns>
        </member>
        <member name="M:AutoCADLibrary.PromptUtil.GetPointResult(System.String,System.Boolean)">
            <summary>
            사용자가 선택한 점을 가져오는 메소드입니다.
            </summary>
            <param name="message">선택 전, 프롬프트에 표시할 메시지</param>
            <returns>사용자의 입력에 대한 결과</returns>
        </member>
        <member name="M:AutoCADLibrary.PromptUtil.GetPointResult(Autodesk.AutoCAD.Geometry.Point3d,System.String,System.Boolean)">
            <summary>
            사용자가 선택한 점을 가져오는 메소드입니다. 점을 선택할 때, BasePoint를 기준으로 대쉬라인이 함께 나타납니다.
            </summary>
            <param name="message">선택 전, 프롬프트에 표시할 메시지</param>
            <param name="BasePoint">기준점의 좌표</param>
            <returns>사용자의 입력에 대한 결과</returns>
        </member>
        <member name="M:AutoCADLibrary.PromptUtil.GetString(System.String,System.Boolean,System.String)">
            <summary>
            사용자로부터 문자열을 입력받습니다.
            </summary>
            <param name="message">입력 전, 프롬프트에 표시할 메시지</param>
            <param name="allowSpace">공백을 포함할 여부입니다.</param>
            <param name="defaultString">기본 지정 문자열입니다.</param>
            <returns></returns>
        </member>
        <member name="M:AutoCADLibrary.PromptUtil.GetCorner(Autodesk.AutoCAD.Geometry.Point3d,System.String)">
            <summary>
            사용자로부터 구역을 선택받습니다.
            </summary>
            <param name="BasePoint">기준점 입니다.</param>
            <param name="message">입력 전, 프롬프트에 표시할 메시지 입니다.</param>
            <returns></returns>
        </member>
        <member name="M:AutoCADLibrary.PromptUtil.ActivateApplication">
            <summary>
            AutoCAD 창을 활성화시킵니다.
            </summary>
        </member>
        <member name="M:AutoCADLibrary.PromptUtil.GetProgressBar(System.String,System.Int32)">
            <summary>
            AutoCAD의 진행바를 정의하여 리턴합니다.
            </summary>
            <param name="message">진행바 진행 시, 어떤 메시지를 출력할지 나타냅니다.</param>
            <param name="limit">진행바의 최대값을 설정합니다.</param>
            <returns></returns>
        </member>
        <member name="M:AutoCADLibrary.PromptUtil.PromptMessage(System.String)">
            <summary>
            AutoCAD에 메세지를 출력합니다.
            </summary>
            <param name="message">출력할 메세지입니다.</param>
        </member>
        <member name="T:AutoCADLibrary.TextUtil">
            <summary>
            MText, DBText에 대한 명령이 들어있는 클래스입니다.
            </summary>
        </member>
        <member name="M:AutoCADLibrary.TextUtil.CreateDBText(System.String,System.Double,Autodesk.AutoCAD.DatabaseServices.AttachmentPoint,System.String,Autodesk.AutoCAD.Colors.Color,Autodesk.AutoCAD.DatabaseServices.ObjectId)">
            <summary>
            Text를 생성합니다.
            </summary>
            <param name="textString">객체에 표현될 문자열입니다.</param>
            <param name="textHeight">객체의 문자높이 입니다.</param>
            <param name="textAttachPoint">객체의 삽입점을 조절합니다.</param>
            <param name="layerName">객체의 레이어를 지정합니다.</param>
            <param name="color">객체의 색깔을 지정합니다.</param>
            <param name="textStyleId">객체에 적용할 TextStyle의 ID입니다.</param>
            <returns></returns>
        </member>
        <member name="M:AutoCADLibrary.TextUtil.GetTextStyleId(System.String)">
            <summary>
            TextStyle을 name으로 찾아줍니다.
            </summary>
            <param name="name">TextStyle의 이름입니다.</param>
            <returns>TextStyle의 ObjectId를 리턴합니다.</returns>
        </member>
    </members>
</doc>
